//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 11:26:05 AM CET 
//


package com.intel.mountwilson.ta.data.quoterequest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="nonce" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="pcr_list" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="IMA" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nonce",
    "pcrList",
    "ima"
})
@XmlRootElement(name = "quote_request", namespace = "")
public class QuoteRequest {

    @XmlElement(required = true)
    protected String nonce;
    @XmlElement(name = "pcr_list", required = true)
    protected String pcrList;
    @XmlElement(name = "IMA")
    protected boolean ima;

    /**
     * Gets the value of the nonce property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNonce() {
        return nonce;
    }

    /**
     * Sets the value of the nonce property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNonce(String value) {
        this.nonce = value;
    }

    /**
     * Gets the value of the pcrList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcrList() {
        return pcrList;
    }

    /**
     * Sets the value of the pcrList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcrList(String value) {
        this.pcrList = value;
    }

    /**
     * Gets the value of the ima property.
     * 
     */
    public boolean isIMA() {
        return ima;
    }

    /**
     * Sets the value of the ima property.
     * 
     */
    public void setIMA(boolean value) {
        this.ima = value;
    }

}
