//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.21 at 10:17:07 AM CET 
//


package com.intel.mountwilson.trustagent.imameasurement;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="File" type="{mtwilson:ima:measurements:1.0}fileMeasurementType"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="DigestAlg" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "imameasurements"
})
@XmlRootElement(name = "IMA_Measurements")
public class IMAMeasurements {

    @XmlElement(name = "File")
    protected List<FileMeasurementType> imameasurements;
    @XmlAttribute(name = "DigestAlg")
    protected String digestAlg;

    /**
     * Gets the value of the imameasurements property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the imameasurements property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImameasurements().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FileMeasurementType }
     * 
     * 
     */
    public List<FileMeasurementType> getImameasurements() {
        if (imameasurements == null) {
            imameasurements = new ArrayList<FileMeasurementType>();
        }
        return this.imameasurements;
    }

    /**
     * Gets the value of the digestAlg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDigestAlg() {
        return digestAlg;
    }

    /**
     * Sets the value of the digestAlg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDigestAlg(String value) {
        this.digestAlg = value;
    }

}
